# Generated by Django 5.2.4 on 2025-07-13 17:07

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50, verbose_name='Nombre del propietario')),
                ('owner_ci', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Cedula del propietario')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Correo del propietario')),
                ('owner_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='VE', verbose_name='Telefono del propietario')),
                ('method', models.CharField(choices=[('P', 'Pago Móvil')], max_length=50, verbose_name='Método de Pago')),
                ('reference', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('V', 'Verificado'), ('E', 'En Espera'), ('C', 'Cancelado')], max_length=50, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('updated_at', models.DateTimeField(verbose_name='Ultima actualización')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('slug', models.SlugField(editable=False, max_length=110, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date_lottery', models.DateTimeField(verbose_name='Fecha del Sorteo')),
                ('prize_picture', models.ImageField(upload_to='premios/', verbose_name='Foto del premio')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio del ticket')),
                ('state', models.CharField(choices=[('B', 'BORRADOR'), ('A', 'ACTIVO'), ('F', 'FINALIZADO'), ('V', 'VENDIDO')], default='B', verbose_name='Estado del sorteo')),
                ('total_tickets', models.PositiveIntegerField(verbose_name='Máxima cantidad de tickets a vender')),
                ('tickets_sold', models.PositiveIntegerField(editable=False, verbose_name='Tickets vendidos')),
                ('is_main', models.BooleanField(default=False, verbose_name='Sorteo Principal')),
            ],
            options={
                'verbose_name': 'Sorteo',
                'verbose_name_plural': 'Sorteos',
                'ordering': ['-is_main', '-date_lottery'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveIntegerField(verbose_name='Número de ticket')),
                ('owner_name', models.CharField(max_length=50, verbose_name='Nombre del propietario')),
                ('owner_ci', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Cedula del propietario')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Correo del propietario')),
                ('owner_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='VE', verbose_name='Telefono del propietario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='sorteo.payment', verbose_name='Pago')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='sorteo.sorteo', verbose_name='Sorteo')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'unique_together': {('serial', 'sorteo')},
            },
        ),
    ]
