# Generated by Django 5.2.4 on 2025-07-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sorteo',
            old_name='tickets_sold',
            new_name='tickets_solds',
        ),
    ]
