# Generated by Django 5.2.4 on 2025-07-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0002_rename_tickets_sold_sorteo_tickets_solds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteo',
            name='is_main',
            field=models.BooleanField(default=False, null=True, verbose_name='Sorteo Principal'),
        ),
    ]
