# Generated by Django 5.2.4 on 2025-07-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0003_alter_sorteo_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteo',
            name='tickets_solds',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Tickets vendidos'),
        ),
    ]
