# Generated by Django 5.2.4 on 2025-07-14 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0004_alter_sorteo_tickets_solds'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sorteo',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sorteo.sorteo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='tickets_quantity',
            field=models.PositiveBigIntegerField(default=12),
            preserve_default=False,
        ),
    ]
