# Generated by Django 5.2.4 on 2025-07-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0005_payment_sorteo_payment_tickets_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='serial',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='Serial de la transacción'),
        ),
    ]
