# Generated by Django 5.2.4 on 2025-07-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0006_payment_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='lottery_conditions',
            field=models.TextField(default='conditions here', verbose_name='Condiciones del sorteo'),
            preserve_default=False,
        ),
    ]
