# Generated by Django 5.2.4 on 2025-07-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0007_sorteo_lottery_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Ultima actualización'),
        ),
    ]
