# Generated by Django 5.2.4 on 2025-07-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0008_alter_payment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='sorteo',
        ),
        migrations.AddField(
            model_name='payment',
            name='transferred_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto transferido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Ultima actualización'),
        ),
    ]
