# Generated by Django 5.2.4 on 2025-07-23 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0009_remove_payment_sorteo_payment_transferred_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sorteo',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sorteo.sorteo'),
            preserve_default=False,
        ),
    ]
