# Generated by Django 5.2.4 on 2025-07-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0010_payment_sorteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_of_transfer',
            field=models.CharField(choices=[('0102', 'Banco de Venezuela'), ('0104', 'Banco Venezolano de Crédito'), ('0105', 'Banco Mercantil'), ('0108', 'Banco Provincial'), ('0114', 'Bancaribe'), ('0115', 'Banco Exterior'), ('0128', 'Banco Caroní'), ('0134', 'Banesco'), ('0137', 'Banco Sofitasa'), ('0138', 'Banco Plaza'), ('0151', 'BFC Banco Fondo Común'), ('0156', '100% Banco'), ('0157', 'DelSur Banco Universal'), ('0163', 'Banco del Tesoro'), ('0166', 'Banco Agrícola de Venezuela'), ('0168', 'Bancrecer'), ('0169', 'Mi Banco'), ('0171', 'Banco Activo'), ('0172', 'Bancamiga'), ('0174', 'Banplus'), ('0175', 'Banco Bicentenario del Pueblo'), ('0177', 'Banfanb'), ('0191', 'BNC Banco Nacional de Crédito')], default='0102', max_length=4, verbose_name='Banco de transferencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='transferred_date',
            field=models.DateField(default='2022-01-02', verbose_name='Fecha de transferencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='type_CI',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('J', 'Jurídico')], default='V', max_length=1, verbose_name='Tipo de cédula'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
