# Generated by Django 5.2.4 on 2025-07-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0011_payment_bank_of_transfer_payment_transferred_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_verification_note',
            field=models.TextField(blank=True, null=True, verbose_name='Nota de verificación del pago'),
        ),
    ]
