# Generated by Django 5.2.4 on 2025-07-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0012_payment_payment_verification_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_payment_registered',
            field=models.BooleanField(default=False, editable=False, verbose_name='Pago registrado'),
        ),
    ]
