# Generated by Django 5.2.4 on 2025-08-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0013_payment_is_payment_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='winner_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ganadores/', verbose_name='Foto del ganador'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('P', 'Pago Móvil'), ('Z', 'Zelle')], max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=30, verbose_name='Referencia del pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tickets_quantity',
            field=models.PositiveBigIntegerField(verbose_name='Cantidad de tickets'),
        ),
    ]
